### ISSUE TITLE
[Feature Request] Monitor Multiple Tags

### ISSUE THREAD

**Issue by msf999** [mlava/unread-badge#1]
Thanks for the wonderful extension!

Would it be possible to add the ability to monitor multiple tags? For example, currently I have an _Inbox_ tag that I am currently using the extension to monitor, but I'd also love to have a badge for my _Questions_ tag to know how many blocks I tagged as questions.

Thank you :)

**Comment by mlava** [comment]
This is a great idea.
I'll add it to the list of things to work on...

**Comment by mlava** [comment]
@msf999 this is now implemented and awaiting review in the Roam Depot github. The Roam team need to review and approve before it will be available in Roam Depot. Let me know if there are any issues once it's available.
